# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test
          BUNDLER_VERSION: 2.0.2
          PGHOST: 127.0.0.1
          PGUSER: root

      - image: circleci/postgres:11.5-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gem install bundler:2.0.2

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle --clean

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m

      - run:
          name: rubocop
          command: bundle exec rubocop

      - run:
          name: test
          command: bundle exec rails test

      # - run:
      #     name: Database setup
      #     command: |
      #       bundle exec rails db:create
      #       bundle exec rails db:migrate

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2

  continuous-integration:
    jobs:
      - build
