# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          RAILS_ENV: test
          BUNDLER_VERSION: 2.0.2
          DATABASE_URL: "postgres://pgadmin@localhost:5432/books_app_test"

      - image: circleci/postgres:11.5-alpine
        environment:
          POSTGRES_USER: pgadmin
          POSTGRES_DB: books_app_test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gem install bundler:2.0.2

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle --clean

      - run:
          name: Set up DB
          command: |
            bundle exec rails db:create db:schema:load --trace
            bundle exec rails db:migrate

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: rubocop
          command: bundle exec rubocop -a

      - run:
          name: test
          command: |
            # bundle exec rails db:schema:load
            bundle exec rails test

      - add_ssh_keys:
          fingerprints:
            - "bc:f4:95:fa:ca:ec:9c:09:7d:c7:80:41:c9:55:d4:da"
      - run:
          name: capistrano deploy
          command: bundle exec cap production deploy

workflows:
  version: 2

  continuous-integration:
    jobs:
      - build
